import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../../controllers/auth_controller.dart';
import '../home/home_screen.dart';

class LoginScreen extends StatefulWidget {
  const LoginScreen({super.key});

    @override
      State<LoginScreen> createState() => _LoginScreenState();
      }

      class _LoginScreenState extends State<LoginScreen> {
        final TextEditingController _phoneController = TextEditingController();
          final TextEditingController _otpController = TextEditingController();
            final TextEditingController _nameController = TextEditingController();
              
                String _selectedRole = 'house_owner';
                  bool _otpSent = false;

                    void _submitPhone() async {
                        final authProvider = Provider.of<AuthController>(context, listen: false);
                            await authProvider.verifyPhoneNumber(
                                  _phoneController.text.trim(),
                                        (verificationId) {
                                                setState(() {
                                                          _otpSent = true;
                                                                  });
                                                                        },
                                                                            );
                                                                              }

                                                                                void _submitOtp() async {
                                                                                    final authProvider = Provider.of<AuthController>(context, listen: false);
                                                                                        bool success = await authProvider.verifyOtp(
                                                                                              _otpController.text.trim(),
                                                                                                    _nameController.text.trim(),
                                                                                                          _selectedRole,
                                                                                                              );

                                                                                                                  if (success && mounted) {
                                                                                                                        Navigator.pushReplacement(context, MaterialPageRoute(builder: (context) => const HomeScreen()));
                                                                                                                            } else {
                                                                                                                                  ScaffoldMessenger.of(context).showSnackBar(
                                                                                                                                          const SnackBar(content: Text('Invalid OTP. Please try again.'))
                                                                                                                                                );
                                                                                                                                                    }
                                                                                                                                                      }

                                                                                                                                                        @override
                                                                                                                                                          Widget build(BuildContext context) {
                                                                                                                                                              final authProvider = Provider.of<AuthController>(context);

                                                                                                                                                                  return Scaffold(
                                                                                                                                                                        body: Container(
                                                                                                                                                                                padding: const EdgeInsets.all(24.0),
                                                                                                                                                                                        alignment: Alignment.center,
                                                                                                                                                                                                child: ConstrainedBox(
                                                                                                                                                                                                          constraints: const BoxConstraints(maxWidth: 500),
                                                                                                                                                                                                                    child: Column(
                                                                                                                                                                                                                                mainAxisAlignment: MainAxisAlignment.center,
                                                                                                                                                                                                                                            crossAxisAlignment: CrossAxisAlignment.stretch,
                                                                                                                                                                                                                                                        children: [
                                                                                                                                                                                                                                                                      const Icon(Icons.construction_rounded, size: 80, color: Colors.amber),
                                                                                                                                                                                                                                                                                    const SizedBox(height: 12),
                                                                                                                                                                                                                                                                                                  const Text('Welcome to MistriHub', style: TextStyle(fontSize: 28, fontWeight: FontWeight.bold), textAlign: TextAlign.center),
                                                                                                                                                                                                                                                                                                                const SizedBox(height: 32),
                                                                                                                                                                                                                                                                                                                              if (!_otpSent) ...[
                                                                                                                                                                                                                                                                                                                                              TextField(
                                                                                                                                                                                                                                                                                                                                                                controller: _nameController,
                                                                                                                                                                                                                                                                                                                                                                                  decoration: const InputDecoration(labelText: 'Full Name', border: OutlineInputBorder()),
                                                                                                                                                                                                                                                                                                                                                                                                  ),
                                                                                                                                                                                                                                                                                                                                                                                                                  const SizedBox(height: 16),
                                                                                                                                                                                                                                                                                                                                                                                                                                  TextField(
                                                                                                                                                                                                                                                                                                                                                                                                                                                    controller: _phoneController,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      keyboardType: TextInputType.phone,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        decoration: const InputDecoration(labelText: 'Phone Number (+91)', border: OutlineInputBorder()),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const SizedBox(height: 16),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        DropdownButtonFormField<String>(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          value: _selectedRole,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            items: const [
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                DropdownMenuItem(value: 'house_owner', child: Text('House Owner')),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    DropdownMenuItem(value: 'contractor', child: Text('Contractor')),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        DropdownMenuItem(value: 'worker', child: Text('Worker')),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            DropdownMenuItem(value: 'advertiser', child: Text('Advertiser')),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                onChanged: (val) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    setState(() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          _selectedRole = val!;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  decoration: const InputDecoration(labelText: 'Register As', border: OutlineInputBorder()),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const SizedBox(height: 24),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ElevatedButton(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    onPressed: authProvider.isLoading ? null : _submitPhone,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      style: ElevatedButton.styleFrom(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          padding: const EdgeInsets.symmetric(vertical: 16),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              backgroundColor: Colors.amber,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  child: authProvider.isLoading ? const CircularProgressIndicator() : const Text('Send Verification Code'),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ] else ...[
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                TextField(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  controller: _otpController,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    keyboardType: TextInputType.number,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      decoration: const InputDecoration(labelText: 'Enter 6-Digit Verification OTP', border: OutlineInputBorder()),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const SizedBox(height: 24),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ElevatedButton(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        onPressed: authProvider.isLoading ? null : _submitOtp,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          style: ElevatedButton.styleFrom(padding: const EdgeInsets.symmetric(vertical: 16)),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            child: authProvider.isLoading ? const CircularProgressIndicator() : const Text('Verify and Login'),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../../controllers/auth_controller.dart';
import '../home/home_screen.dart';

class LoginScreen extends StatefulWidget {
  const LoginScreen({super.key});

  @override
  State<LoginScreen> createState() => _LoginScreenState();
}

class _LoginScreenState extends State<LoginScreen> {
  final TextEditingController _phoneController = TextEditingController();
  final TextEditingController _otpController = TextEditingController();
  final TextEditingController _nameController = TextEditingController();
  
  String _selectedRole = 'house_owner';
  bool _otpSent = false;

  void _submitPhone() async {
    final authProvider = Provider.of<AuthController>(context, listen: false);
    await authProvider.verifyPhoneNumber(
      _phoneController.text.trim(),
      (verificationId) {
        setState(() {
          _otpSent = true;
        });
      },
    );
  }

  void _submitOtp() async {
    final authProvider = Provider.of<AuthController>(context, listen: false);
    bool success = await authProvider.verifyOtp(
      _otpController.text.trim(),
      _nameController.text.trim(),
      _selectedRole,
    );

    if (success && mounted) {
      Navigator.pushReplacement(context, MaterialPageRoute(builder: (context) => const HomeScreen()));
    } else {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Invalid OTP. Please try again.'))
      );
    }
  }

  @override
  Widget build(BuildContext context) {
    final authProvider = Provider.of<AuthController>(context);

    return Scaffold(
      body: Container(
        padding: const EdgeInsets.all(24.0),
        alignment: Alignment.center,
        child: ConstrainedBox(
          constraints: const BoxConstraints(maxWidth: 500),
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              const Icon(Icons.construction_rounded, size: 80, color: Colors.amber),
              const SizedBox(height: 12),
              const Text('Welcome to MistriHub', style: TextStyle(fontSize: 28, fontWeight: FontWeight.bold), textAlign: TextAlign.center),
              const SizedBox(height: 32),
              if (!_otpSent) ...[
                TextField(
                  controller: _nameController,
                  decoration: const InputDecoration(labelText: 'Full Name', border: OutlineInputBorder()),
                ),
                const SizedBox(height: 16),
                TextField(
                  controller: _phoneController,
                  keyboardType: TextInputType.phone,
                  decoration: const InputDecoration(labelText: 'Phone Number (+91)', border: OutlineInputBorder()),
                ),
                const SizedBox(height: 16),
                DropdownButtonFormField<String>(
                  value: _selectedRole,
                  items: const [
                    DropdownMenuItem(value: 'house_owner', child: Text('House Owner')),
                    DropdownMenuItem(value: 'contractor', child: Text('Contractor')),
                    DropdownMenuItem(value: 'worker', child: Text('Worker')),
                    DropdownMenuItem(value: 'advertiser', child: Text('Advertiser')),
                  ],
                  onChanged: (val) {
                    setState(() {
                      _selectedRole = val!;
                    });
                  },
                  decoration: const InputDecoration(labelText: 'Register As', border: OutlineInputBorder()),
                ),
                const SizedBox(height: 24),
    