import 'package:flutter/material.dart';
import 'package:cloud_firestore/cloud_firestore.dart';

class AdminDashboardScreen extends StatelessWidget {
  const AdminDashboardScreen({super.key});

    @override
      Widget build(BuildContext context) {
          return Scaffold(
                appBar: AppBar(
                        title: const Text('Admin Console Hub'),
                                backgroundColor: Colors.black87,
                                      ),
                                            body: Row(
                                                    children: [
                                                              NavigationRail(
                                                                          selectedIndex: 0,
                                                                                      onDestinationSelected: (int val) {},
                                                                                                  labelType: NavigationRailLabelType.all,
                                                                                                              destinations: const [
                                                                                                                            NavigationRailDestination(icon: Icon(Icons.verified_user), label: Text('Verifications')),
                                                                                                                                          NavigationRailDestination(icon: Icon(Icons.campaign), label: Text('Ad Campaigns')),
                                                                                                                                                        NavigationRailDestination(icon: Icon(Icons.report_problem), label: Text('Moderation')),
                                                                                                                                                                    ],
                                                                                                                                                                              ),
                                                                                                                                                                                        const VerticalDivider(thickness: 1, width: 1),
                                                                                                                                                                                                  Expanded(
                                                                                                                                                                                                              child: StreamBuilder<QuerySnapshot>(
                                                                                                                                                                                                                            stream: FirebaseFirestore.instance.collection('workers').snapshots(),
                                                                                                                                                                                                                                          builder: (context, snapshot) {
                                                                                                                                                                                                                                                          if (!snapshot.hasData) return const Center(child: CircularProgressIndicator());
                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                          final workers = snapshot.data!.docs;
                                                                                                                                                                                                                                                                                                          return ListView.builder(
                                                                                                                                                                                                                                                                                                                            itemCount: workers.length,
                                                                                                                                                                                                                                                                                                                                              itemBuilder: (context, index) {
                                                                                                                                                                                                                                                                                                                                                                  var data = workers[index].data() as Map<String, dynamic>;
                                                                                                                                                                                                                                                                                                                                                                                      bool verified = data['isVerified'] ?? false;
                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                              return ListTile(
                                                                                                                                                                                                                                                                                                                                                                                                                                                    title: Text(data['name'] ?? ''),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          subtitle: Text('${data['category']} - ${data['city']}'),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                trailing: Checkbox(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        value: verified,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                onChanged: (bool? newValue) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          FirebaseFirestore.instance
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        .collection('workers')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      .doc(workers[index].id)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    .update({'isVerified': newValue ?? false});
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }import 'package:flutter/material.dart';
import 'package:cloud_firestore/cloud_firestore.dart';

class AdminDashboardScreen extends StatelessWidget {
  const AdminDashboardScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Admin Console Hub'),
        backgroundColor: Colors.black87,
      ),
      body: Row(
        children: [
          NavigationRail(
            selectedIndex: 0,
            onDestinationSelected: (int val) {},
            labelType: NavigationRailLabelType.all,
            destinations: const [
              NavigationRailDestination(icon: Icon(Icons.verified_user), label: Text('Verifications')),
              NavigationRailDestination(icon: Icon(Icons.campaign), label: Text('Ad Campaigns')),
              NavigationRailDestination(icon: Icon(Icons.report_problem), label: Text('Moderation')),
            ],
          ),
          const VerticalDivider(thickness: 1, width: 1),
          Expanded(
            child: StreamBuilder<QuerySnapshot>(
              stream: FirebaseFirestore.instance.collection('workers').snapshots(),
              builder: (context, snapshot) {
                if (!snapshot.hasData) return const Center(child: CircularProgressIndicator());
                
                final workers = snapshot.data!.docs;
                return ListView.builder(
                  itemCount: workers.length,
                  itemBuilder: (context, index) {
                    var data = workers[index].data() as Map<String, dynamic>;
                  